name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the master branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    # Runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.16.0'  # Replace with the desired Node.js version  node-version: '16.14.0'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.9.2'  #version: '8.6.8'
          
      
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.yaml') }}
          
      - name: Install dependencies
        run: pnpm i
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Build app
        run: pnpm run build

      # If you need to deploy the built files to a server, you can add the deployment step here
      - name: 连接到服务器并删除目标文件夹内容
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf /firework/*
           
      - name: 上传文件到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # 服务器地址
          username: ${{ secrets.SERVER_USERNAME }}  # 服务器登录用户名
          password: ${{ secrets.SERVER_PASSWORD }}  # 服务器登录密码，需要在 Secrets 中设置
          # key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH私钥，需要在 Secrets 中设置
          # 构建后文件的本地路径，这里假设打包后的文件在 "dist" 目录下
          source: "docs/"

          # 上传到服务器的目标路径，这里是服务器上的目标路径
          target: "/firework"